# Generated by Django 4.0.3 on 2022-04-22 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parallel', models.CharField(choices=[('a', 'А'), ('b', 'Б'), ('v', 'В'), ('g', 'Г')], max_length=1, verbose_name='параллель')),
                ('start_year', models.IntegerField(default=2022)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128, verbose_name='имя')),
                ('surname', models.CharField(max_length=128, verbose_name='фамилия')),
                ('age', models.PositiveIntegerField()),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.grade', verbose_name='Класс')),
            ],
        ),
    ]
